apiVersion: v1
kind: Service
metadata:
  name: nginx-backend
  namespace: default
spec:
  selector:
    app: nginx-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP