apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
  namespace: default
data:
  index.html: |
   <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hello Kubernetes</title>
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
    </body>
    </html>