apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
  namespace: ingress-nginx
data:
  index.html: |
    <html>
      <body>
        <h1>Hello, Kubernetes!</h1>
      </body>
    </html>